#!/bin/bash

Install SonarQube

sudo yum update -yum
sudo yum install java-11-open jdk-devel -yum
sudo yum install java-11-openjdk -yum

cd /opt

sudo yum install wget -yum
sudo wget https://binaries.sonarsource.com/develDistribution/sonarqube/sonarqube-9.3.0.51899.zip

sudo unzip /opt/sonarqube-9.3.0.518999.zip
sudo unzip /opt/sonarqube-9.3.0.518999.zip

sudo chown -R vagrant:vagrant /opt/sonarqube-9.3.0.51899
cd /opt/sonarqube-x.x/bin/linux-x86-64
./sonar.sh start